name: Outdated package checks

# Run workflow on pull request to the main branch
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main, master ]
    paths:
      - '.github/workflows/outdated.yml'
      - 'TxnNetwork.ApiDocumentation/**'
  
  workflow_dispatch:

env:
  SOLUTION_PATH: 'TxnNetwork.ApiDocumentation/TxnNetwork.ApiDocumentation.sln'
  PROJECT_DIR: 'TxnNetwork.ApiDocumentation/TxnNetwork.ApiDocumentation'

jobs:
  outdated-packages-check:
    runs-on: ubuntu-latest

    steps:
      - uses: trossr32/outdated-packages-action@v1.4.1
        with:
          use-dotnet-outdated: true
          dotnet-solution-or-project-path: ${{ env.SOLUTION_PATH }}
          use-npm-outdated: true
          npm-project-directory: ${{ env.PROJECT_DIR }}